### ISSUE TITLE
Custom Titlebar

### ISSUE THREAD

**Issue by Lakelimbo** [codesbiome/electron-react-webpack-typescript-2021#19]
I'm trying to use [https://github.com/AlexTorresSk/custom-electron-titlebar](url) with this boilerplate, but it's always resulting in `errno: -4068`. I tried to use this on index.html, but then other errors (such as `require is not defined`) shows.
How can I implement this package into this boilerplate? :)

**Comment by codesbiome** [comment]
@Lakelimbo can you give it a try: 
https://github.com/codesbiome/electron-react-webpack-typescript-2021/issues/18#issuecomment-926057413

**Comment by Lakelimbo** [comment]
Hello again, sorry for taking so long, I got some other things to do recently.
I actually did enable nodeIntegration and set contextIsolation to 'false', however if I try to add the code to generate the titlebar on Application.tsx, the project does not compile and throws an error.

On Application.tsx
```
import { Titlebar, Color } from 'custom-electron-titlebar';

new Titlebar({
	backgroundColor: Color.fromHex('#ECECEC')
});

...
```

Error:
```
An unhandled rejection has occurred inside Forge:
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'read'
}

Electron Forge was terminated. Location:
{}
error Command failed with exit code 1.
```
