### ISSUE TITLE
Webpack entryPoints name

### ISSUE THREAD

**Issue by panpansh** [codesbiome/electron-react-webpack-typescript-2021#21]
can we move files from .webpack/renderer/app_window/ to .webpack/renderer/

I try to use react-router with nested routes and to avoid problems it can be better to have files at the root of renderer folder.

Best Regards.

https://github.com/codesbiome/electron-react-webpack-typescript-2021/issues/21#issuecomment-990243028

**Comment by codesbiome** [comment]
Hello @panpansh 

 Seems like there is no such configuration option available, to have files at the root of renderer folder.
Electron Forge's [Webpack Plugin](https://github.com/electron-userland/electron-forge/blob/master/packages/plugin/webpack/src/WebpackConfig.ts#L183) requires an `entryPoint` name to separate the context (in case of multiple windows process). 

Maybe you can try use `react-router-dom` instead of react-touter.

**Comment by panpansh** [comment]
@codesbiome thanks for your reply.
yes im using this one
``` jsx
<BrowserRouter>
    <WindowFrame title='ERWT Boilerplate' platform='windows'>
      <Routes>
        <Route path="/app_window" element={<Application />} />
        <Route path="expenses" element={<Expenses />} />
        <Route path="invoices" element={<Invoices />} />
      </Routes>
    </WindowFrame>
  </BrowserRouter>
```
but nested routes not
```jsx
<BrowserRouter>
    <WindowFrame title='ERWT Boilerplate' platform='windows'>
      <Routes>
        <Route path="/app_window" element={<Application />}>
          <Route path="expenses" element={<Expenses />} />
          <Route path="invoices" element={<Invoices />} />
        </Route>
      </Routes>
    </WindowFrame>
  </BrowserRouter>
  // No routes matched location "/expenses"
  // No routes matched location "/invoices"
```

**Comment by panpansh** [comment]
ok looking the code in @electron-forge/plugin-webpack/WebpackConfig.js:83

```js
toEnvironmentVariable()
```
I just replaced const name and set name to empty string in forge config
```comment
APP_WINDOW_WEBPACK_ENTRY and APP_WINDOW_PRELOAD_WEBPACK_ENTRY
to
_WEBPACK_ENTRY and _PRELOAD_WEBPACK_ENTRY
```
now i need to fix the index.js location : 
![image](https://user-images.githubusercontent.com/790586/145224518-8684eb77-00f8-4485-bfaa-1ab87bcbd437.png)

**Comment by panpansh** [comment]
@electron-forge/plugin-webpack/WebpackConfig.js:211
```js
filename: this.pluginConfig.renderer.entryPoints.length === 1 ? 'index.js' : '[name]/index.js',
```
![image](https://user-images.githubusercontent.com/790586/145226411-9e7d66ae-959f-468c-9c0e-55bf9c4ed667.png)

**Comment by panpansh** [comment]
the UI display, counter work, but not my links :/

**Comment by codesbiome** [comment]
> yes im using this one react-router-dom
> here working but not nested and strange

```jsx
<BrowserRouter>
    <WindowFrame title='ERWT Boilerplate' platform='windows'>
      <Routes>
        <Route path="/app_window" element={<Application />} />
        <Route path="expenses" element={<Expenses />} />
        <Route path="invoices" element={<Invoices />} />
      </Routes>
    </WindowFrame>
  </BrowserRouter>
```

Using `BrowseRouter` might also cause some issues with routing, specially when building the app for distribution (Production).

Also not sure why `/app_window` is being used instead of just `/`, is there any specific reason to use that Route path?

Something simple with using `HashRouter` might work :

```jsx
// ... Other imports
import { HashRouter as Router } from 'react-router-dom';

// Application to Render
const app = (
  <Router>
      <WindowFrame title='ERWT Boilerplate' platform='windows'>
        <Routes>
          <Route path="/expenses" element={<Expenses />} />
          <Route path="/invoices" element={<Invoices />} />
          <Route path='/' element={<Application/>} />
        </Routes>
      </WindowFrame>
    </StoreProvider>
  </Router>
);
```

**Comment by panpansh** [comment]
the current problem I have with my changes is in development mode he give me the good path

```html
<script defer src="/index.js"></script>
<link href="/assets/7bf2b3737dfbbf561dbd.css" rel="stylesheet">
```

but for production when I make I get this path :/
```html
<script defer="defer" src="Users/panpansh/Desktop/test_app/.webpack/renderer/index.js"></script>
<link href="Users/panpansh/Desktop/test_app/.webpack/renderer/assets/c02c3fd55c60c9305d15.css" rel="stylesheet">
```

**Comment by panpansh** [comment]
ok here if my fix from start : 

src/main/appWindow.ts
```tsx
declare const _ROOT_WEBPACK_ENTRY: string;
declare const _ROOT_PRELOAD_WEBPACK_ENTRY: string;
...
preload: _ROOT_PRELOAD_WEBPACK_ENTRY,
...
appWindow.loadURL(_ROOT_WEBPACK_ENTRY);
// use _ROOT as key 
```

tools/forge/forge.config.js
```comment
// Window process name
name: '.',
// this dot is used to be the current dir (like root) of renderer
```

@electron-forge/plugin-webpack/WebpackConfig.js:85
```jsx
return `${this.pluginConfig.renderer.entryPoints.length === 1 && this.pluginConfig.renderer.entryPoints[0].name === '.' ? '_ROOT' : entryPoint.name.toUpperCase().replace(/ /g, '_')}${suffix}`;
// if the name is dot '.' use '_ROOT' as prefix for EnvironmentVariable
```

here you have files at root of render and it seems all is working fine. until next comment 😂

**Comment by panpansh** [comment]
let me know if we can integrate react dev tools please if you already done this :)

**Comment by panpansh** [comment]
Thank you for this https://github.com/codesbiome/electron-react-webpack-typescript-2021/issues/21#issuecomment-988992783
Let me know how we can simply debug routes.
btw all working fine <3

**Comment by codesbiome** [comment]
> let me know if we can integrate react dev tools please if you already done this :)


React devtools can be used by installing `electron-devtools-installer` package and implementing extension installer in `main/app.ts`

```ts
// app.ts

import { app, BrowserWindow } from 'electron';
import installExtension, { REACT_DEVELOPER_TOOLS } from 'electron-devtools-installer';
import { createAppWindow } from './appWindow';

app.on('ready', createAppWindow);

/**
 * Devtools Extension Installer
 */
app.whenReady().then(() => {
    installExtension(REACT_DEVELOPER_TOOLS)
        .then((name) => console.log(`Added Extension:  ${name}`))
        .catch((err) => console.log('An error occurred: ', err));
});

//.....
```

**Comment by panpansh** [comment]
Its perfect much thanks. It's very appreciated
