### ISSUE TITLE
looking app.asar content after make

### ISSUE THREAD

**Issue by panpansh** [codesbiome/electron-react-webpack-typescript-2021#22]
```sh
npx asar extract app.asar ./content
```

I can see : 
```
app.asar
content/ (app.asar extracted)
├─ .webpack/
│  ├─ main/
│  │  ├─ ....
│  ├─ renderer/
│  │  ├─ ....
├─ node_modules/ (empty)
├─ package.json
```
can we change the .webpack folder name ?
do you know if package.json is really used and can be removed ?
can we remove the empty node_modules folder ?

Regards <3

**Comment by panpansh** [comment]
ok all of that can be done by editing two files

```
node_modules\@electron-forge\plugin-webpack\dist\WebpackConfig.js
node_modules\@electron-forge\plugin-webpack\dist\WebpackPlugin.js
```

by example we can remove the node_modules empty folder by commenting line 184 of WebpackPlugin.js
```
//await _fsExtra.default.mkdirp(_path.default.resolve(buildPath, 'node_modules'));
```

then we can make a minimal package.json to copy inside

**Comment by codesbiome** [comment]
**app.asar** creation can be disabled by using `asar: false` in the configuration `tools/forge/forge.config.js` file

```js
  // Packager Config
  packagerConfig: {
    // Create asar archive for main, renderer process files
    asar: false, 
    // Set executable name
    executableName: 'ERWT Boilerplate',
    // Set application copyright
    appCopyright: 'Copyright (C) 2021 Codesbiome, Guasam',
  },
```
<br>

> do you know if package.json is really used and can be removed ?

Removing `package.json` might cause execution related isssues for the packaged output `ERWT Boilerplate.exe`.

**Comment by panpansh** [comment]
thank you for all this constructive discussion
